experiment_name: "baseline_fxnet_poly_disc"

data:
  dataset_root: "../datasets/GUITAR-FX-DIST/Poly_Discrete"
  spectra_folder: "mel_22050_1024_512"
  processed_settings_csv: "proc_settings.csv"
  excl_folders: ["MT2"]
  max_num_settings: 3
  cache_in_ram: true
  test_train_split: 0.8
  val_train_split: 0.1
  shuffle: true
  seed: 42

training:
  batch_size: 100
  epochs: 30
  learning_rate: 0.001
  num_workers: 0

output:
  checkpoints_dir: "checkpoints/baseline_poly_disc"
  results_dir: "results/baseline_poly_disc"
